pipeline{
    agent {
      label 'linux'
    }
    stages{
        stage("Build front"){
            agent {
                docker {
                  label 'linux' 
                  image 'node:13.3.0-alpine3.10' 
                  args '-u root'
                }
            }
            steps{
                sh '''
                    cd ${WORKSPACE}/frontend
                    npm i
                    npm run build
                '''
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
        stage("Pack docker image"){
            steps{
                withDockerRegistry([credentialsId: 'b2ad52d0-aab7-437d-8170-b8c4b4600821', url: 'http://10.0.10.177/repository/docker-dev/']) {
                    sh '''
                    docker build -t frontend --build-arg NGINX_CFG_PATH=ci/front-nginx --build-arg ARTIFACT_PATH=frontend/build ci/Front-dockerfile
                    docker push frontend:${VERSION}
                    '''
                }
            }
            post{
                always{
                    echo "====++++always++++===="
                }
                success{
                    echo "====++++Pack docker image executed succesfully++++===="
                }
                failure{
                    echo "====++++Pack docker image execution failed++++===="
                }
        
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}