version: 0.0
os: linux
hooks:
  ApplicationStart:
    - location: scripts/start_app
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_app
      timeout: 300
      runas: root